name: sys-dia-log Master Branch Workflow

on:
  push:
    branches:
      - 'master'

jobs:

  verify:
    name: Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Amazon Corretto JDK 11
        run: |
          download_url="https://corretto.aws/downloads/resources/11.0.10.9.1/amazon-corretto-11.0.10.9.1-linux-x64.tar.gz"
          wget -O $RUNNER_TEMP/amazon-corretto-11.0.10.9.1-linux-x64.tar.gz $download_url

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/amazon-corretto-11.0.10.9.1-linux-x64.tar.gz
          java-version: '11.0'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Java Test Coverage
        run: ./gradlew jacocoTestReport
        env:
          ENV_AUTH0_CLIENT_ID: ${{ secrets.ENV_AUTH0_CLIENT_ID }}
          ENV_AUTH0_CLIENT_SECRET: ${{ secrets.ENV_AUTH0_CLIENT_SECRET }}
          ENV_AUTH0_DOMAIN: ${{ secrets.ENV_AUTH0_DOMAIN }}

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Flutter Test Coverage
        working-directory: ./mobile
        run: flutter test --coverage

      - name: Publish Test Report
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: ./server/build/reports/jacoco/test/jacocoTestReport.xml, ./mobile/coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true

      - name: Sonar Scan
        run: ./gradlew build sonarqube --info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          ENV_AUTH0_CLIENT_ID: ${{ secrets.ENV_AUTH0_CLIENT_ID }}
          ENV_AUTH0_CLIENT_SECRET: ${{ secrets.ENV_AUTH0_CLIENT_SECRET }}
          ENV_AUTH0_DOMAIN: ${{ secrets.ENV_AUTH0_DOMAIN }}

      - name: Cache SonarCloud packages
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

  docker:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: [ verify ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Amazon Corretto JDK 11
        run: |
          download_url="https://corretto.aws/downloads/resources/11.0.10.9.1/amazon-corretto-11.0.10.9.1-linux-x64.tar.gz"
          wget -O $RUNNER_TEMP/amazon-corretto-11.0.10.9.1-linux-x64.tar.gz $download_url

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/amazon-corretto-11.0.10.9.1-linux-x64.tar.gz
          java-version: '11.0'

      - name: Docker
        #if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: ./gradlew bootBuildImage --publishImage
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          ENV_AUTH0_CLIENT_ID: ${{ secrets.ENV_AUTH0_CLIENT_ID }}
          ENV_AUTH0_CLIENT_SECRET: ${{ secrets.ENV_AUTH0_CLIENT_SECRET }}
          ENV_AUTH0_DOMAIN: ${{ secrets.ENV_AUTH0_DOMAIN }}

  mobile:
    name: Build mobile
    runs-on: macos-latest
    needs: [ verify ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Amazon Corretto JDK 11
        run: |
          download_url="https://corretto.aws/downloads/resources/11.0.10.9.1/amazon-corretto-11.0.10.9.1-macosx-x64.tar.gz"
          wget -O $RUNNER_TEMP/amazon-corretto-11.0.10.9.1-linux-x64.tar.gz $download_url

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/amazon-corretto-11.0.10.9.1-linux-x64.tar.gz
          java-version: '11.0'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Build Flutter
        working-directory: ./mobile
        run: |
          flutter build apk
          flutter build ios --release --no-codesign
